run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - unused
    - revive
  disable:
    - govet

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  max-same-issues: 5
  max-issues-per-linter: 0
  max-issues: 50
