version:  "3.8"

services:
  app:
    restart: always
    build: .bin/main
    command: make run
    ports:
      - "8080"
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - CONFIG_PATH=${CONFIG_PATH}
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
volumes:
  app:
  db:

