version:  "3.8"

services:
  app:
    build: .
    command: make run
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - CONFIG_PATH=${CONFIG_PATH}
    networks:
      - app_network
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
    networks:
      - app_network
networks:
  app_network:
    driver: bridge

volumes:
  pgdata: