env: "local"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  dbname: "postgres"
  max_attempts: 10

servers:
  http:
    port: "8080"
    host: "localhost"
    timeout: 4s
    idle_timeout: 60s