env: "development"

database:
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  dbname: "postgres"
  max_attempts: 10

servers:
  http:
    port: 8080
    host: "127.0.0.1"
    timeout: 4
    idle_timeout: 60